class TelemetryAttributes:
    """
    This class contains the telemetry attributes that are used to log telemetry data.
    We want to make sure the attributes are consistent across the codebase so we can filter on them similarly in datadog.
    Keep it sorted alphabetically to make it easier to find the attribute you are looking for.
    """

    ATS_STREAMING: str = "ats_streaming"
    AUTH_URL: str = "auth_url"
    BATCH_NUMBER: str = "batch_number"
    BATCH_SIZE: str = "batch_size"
    BATCH_SIZE_FOR_SENDING_TO_FHIR_SERVER: str = "batch_size_for_sending_to_fhir_server"
    CHUNK_INDEX: str = "chunk_index"
    CLIENT_ID: str = "client_id"
    CLIENT_PERSON_ID: str = "client_person_id"
    CONNECTION_TYPE: str = "connection_type"
    COUNT: str = "count"
    COUNT_OF_ERRORS: str = "count_of_errors"
    COUNT_OF_RESOURCES: str = "count_of_resources"
    COUNT_OF_RETRIES: str = "count_of_retries"
    DESIRED_PARTITIONS: str = "desired_partitions"
    DESTINATION_FHIR_SERVER: str = "destination_fhir_server"
    ENABLE_AUTOMATIC_PARTITIONS: str = "enable_automatic_partitions"
    ENABLE_TOKEN_STREAMING: str = "enable_token_streaming"
    FLOW_NAME: str = "flow_name"
    HAS_EXPIRY: str = "has_expiry"
    LIMIT: str = "limit"
    MAXIMUM_CONCURRENT_TASKS: str = "maximum_concurrent_tasks"
    MAX_CHUNK_SIZE: str = "max_chunk_size"
    METRIC_COUNT: str = "metric_count"
    METRIC_TYPE: str = "metric_type"
    METRIC_WRITER: str = "metric_writer"
    METRICS_BATCH_SIZE: str = "metrics_batch_size"
    METRICS_BUFFER_LENGTH: str = "metrics_buffer_length"
    NEW_TOKENS_ONLY: str = "new_tokens_only"
    PARTITION_INDEX: str = "partition_index"
    PATIENT_ID: str = "patient_id"
    PIPELINE_CATEGORY: str = "pipeline_category"
    PROCESS_CHUNKS_IN_PARALLEL: str = "process_chunks_in_parallel"
    PROCESSOR_NAME: str = "processor_name"
    RANGE: str = "range"
    REQUEST_SIZE: str = "request_size"
    RESOURCE_TYPE: str = "resource_type"
    RUN_INTELLIGENCE_LAYER: str = "run_intelligence_layer"
    SKIP: str = "skip"
    SLUG: str = "slug"
    SLUG_DISPLAY_NAME: str = "slug_display_name"
    SOURCE: str = "source"
    SOURCE_FHIR_SERVER: str = "source_fhir_server"
    SOURCE_PATIENT_ID: str = "source_patient_id"
    STATUS_CODE: str = "status_code"
    TASK_INDEX: str = "task_index"
    TOKEN_STATUS: str = "token_status"
    URL: str = "url"
    USE_DATA_STREAMING: str = "use_data_streaming"
