# This workflows will upload a Python Package using Twine when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

name: Upload Python Package

on:
  release:
    types: [created]

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Set release tag in VERSION
      run: |
        echo "${{ github.event.release.tag_name }}" > VERSION

    - name: Determine Release Type
      id: release-type
      run: |
        if [[ "${{ github.event.release.prerelease }}" == "true" ]]; then
          echo "Publishing pre-release version"
          echo "is_prerelease=true" >> $GITHUB_OUTPUT
        else
          echo "Publishing stable release"
          echo "is_prerelease=false" >> $GITHUB_OUTPUT
        fi

    - name: build docker
      run: docker compose build --parallel

    - name: Build and publish package with Docker Compose
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI }}
      run: |
        docker compose run --rm -u root -e TWINE_USERNAME=${TWINE_USERNAME} -e TWINE_PASSWORD=${TWINE_PASSWORD} dev sh -c "
          chmod -R 777 /usr/src/helixcore &&
          pip install --upgrade pip &&
          pip install twine wheel &&
          python setup.py sdist bdist_wheel &&
          if [[ '${{ steps.release-type.outputs.is_prerelease }}' == 'true' ]]; then
            twine upload --pre dist/*
          else
            twine upload dist/*
          fi
        "

    - name: list files in dist
      run: ls -haltR dist

    - name: Persist wheels directory
      uses: actions/upload-artifact@v4
      with:
        name: wheel_${{ github.event.release.tag_name }}
        path: dist/*.whl  # Only upload wheel files
        if-no-files-found: error
